CREATE VIEW Tag_Photo_ID_Count_Pairs AS
SELECT T.TAG_PHOTO_ID, COUNT(T.TAG_PHOTO_ID) AS Tag_Photo_ID_Count
FROM jiaqni.PUBLIC_TAGS T
GROUP BY T.TAG_PHOTO_ID
HAVING COUNT(*) >= 1;

CREATE VIEW High_Tag_Photo_Info AS
SELECT TC.TAG_PHOTO_ID, P.PHOTO_ID, P.PHOTO_LINK, P.ALBUM_ID, A.ALBUM_NAME
FROM jiaqni.PUBLIC_TAGS T, jiaqni.PUBLIC_PHOTOS P, jiaqni.PUBLIC_ALBUMS A, Tag_Photo_ID_Count_Pairs TC
WHERE P.ALBUM_ID = A.ALBUM_ID AND TC.TAG_PHOTO_ID = T.TAG_PHOTO_ID
ORDER BY TC.Tag_Photo_ID_Count DESC, T.TAG_PHOTO_ID ASC;

SELECT * FROM High_Tag_Photo_Info;

CREATE VIEW High_Tag_Photo_IDS AS
SELECT TAG_PHOTO_ID FROM High_Tag_Photo_Info;

DROP VIEW High_Tag_Photo_Info;
DROP VIEW Tag_Photo_ID_Count_Pairs;
DROP VIEW High_Tag_Photo_IDS;