CREATE VIEW USER_IDS_NO_FRIENDS AS 
SELECT F.User1_ID
FROM jiaqni.PUBLIC_FRIENDS F
GROUP BY F.USER1_ID
HAVING COUNT(F.USER2_ID) = 0;

SELECT U.User_ID, U.First_Name, U.Last_Name
FROM jiaqni.PUBLIC_USERS U
WHERE U.User_ID IN (SELECT * FROM USER_IDS_NO_FRIENDS);

DROP VIEW USER_IDS_NO_FRIENDS;