CREATE VIEW SAME_TOWNS_USERS_ID AS
SELECT UC.USER_ID
FROM jiaqni.PUBLIC_User_Current_City UC, jiaqni.PUBLIC_User_Hometown_City UH
WHERE UC.USER_ID = UH.USER_ID AND UC.CURRENT_CITY_ID IS NOT NULL AND UH.HOMETOWN_CITY_ID IS NOT NULL 
        AND UC.CURRENT_CITY_ID <> UH.HOMETOWN_CITY_ID;

SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
FROM jiaqni.PUBLIC_USERS U
WHERE U.USER_ID IN (SELECT * FROM SAME_TOWNS_USERS_ID)
ORDER BY U.USER_ID ASC;