DROP TRIGGER order_friends_pairs;
DROP TABLE FRIENDS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE USER_HOMETOWN_CITIES;
DROP SEQUENCE CITIES_ID_SEQUENCE;
DROP TABLE MESSAGES;
DROP TABLE EDUCATION;
DROP SEQUENCE PROGRAMS_ID_SEQUENCE;
DROP TABLE PROGRAMS;
DROP TABLE TAGS; 
DROP TABLE PHOTOS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE USER_EVENTS;
DROP TABLE CITIES;
DROP TABLE USERS;

/*Annie Chen may have also contributed to the development of this file*/